controllers/BaseController.php
<?php
    namespace app\controllers;

    use app\models\DigestModel;
    use app\models\Tgroups;
    use Yii;
    use yii\helpers\Html;
    use yii\web\Controller;
    use yii\web\Request;
    use yii\web\Response;
    use yii\web\Session;
    use yii\helpers\Url;
    use app\models\Teach;
    use yii\helpers\Json;
    use yii\helpers\ArrayHelper;
    use app\models\BaseModel;
    use app\models\UploadedFileModel;
    use app\models\ImageModel;
    use app\models\DigestMaterials;

    class BaseController extends Controller
    {
        /**
         * function for do not write every time Yii:app->request->post('')
         * @param $param
         * @return array|mixed
         */

    protected function c_post($param){
        return Yii::$app->request->post($param);
    }

    public function init()
    {
        $session = new Session;
        $session->open();

        if ( is_null($this->c_post('curl')) ) {
            if (!$session->has('id_teach')) {
                header("Location:" . Url::toRoute('/login'));
                //return \Yii::$app->response->redirect(Url::toRoute('/login'));
                exit();
            }
        }
    }

    public function actionGetCityPrefix()
    {
        return BaseModel::getPrefix();
    }

    public function actionGetAllTeach($return = false) {
        $session = new Session;
        $session->open();
        $role = $session->get('role');
        if ($role != 3) {
            return false;
        }

        $model = new Teach();
        $all_teach = $model->find()->where(['arc_teach' => 0])->orderBy('fio_teach')->asArray()->all();
        $i=0;
        $res = array();
        foreach($all_teach as $value) {
            $res[$value['id_teach']] = $value['fio_teach'];
            //$res[$i]['id_teach'] = $value['id_teach'];
            $i++;
        }
        if($return){
            return $res;
        } else {
            echo Json::encode($res);
        }
    }

    public function actionForType(){
        if(\Yii::$app->request->isAjax) {

            $view = Yii::$app->request->post('type');

            $data = [
                'model' => [
                    'file'      => new UploadedFileModel(),
                    'digest'    => new DigestMaterials(),
                    'image'     => new ImageModel(),
                ],
            ];

            return $this->renderPartial($view, $data);
        }
    }

    public function actionGetGroupsByTeach(){
        if(\Yii::$app->request->isAjax) {
            $group = new Tgroups();
            $id_teach = Yii::$app->request->post('id_teach');
            $groups = $group->getActGroups($id_teach);
            echo Json::encode($groups);
        }
    }

    public function actionGetStudByGroup(){
        if(\Yii::$app->request->isAjax) {
            $group = new DigestModel();
            $id_tgroups = Yii::$app->request->post('id_tgroups');
            $students = $group->getStudByGroups($id_tgroups);
            echo Json::encode($students);
        }
    }

    public function actionLogout()
    {
        $session = new Session;
        $session->destroy();
        Yii::$app->response->redirect(array('/'));
    }


    public function actionChangePassword()
    {
        $session = new Session;
        $session->open();
        $id_teach = $session->get('id_teach');
        $request = Yii::$app->request;
        $pass = $request->post('pass');
        $pass_repeat = $request->post('pass_repeat');
        $model = new Teach();
        $result = $model->changePassword($id_teach,$pass,$pass_repeat);
        if($result == 1)
            echo json_encode(array('msg'=>1));
        elseif($result =='not_empty_pass')
            echo json_encode(array('msg'=>$result));
        elseif($result =='pass_not_match')
            echo json_encode(array('msg'=>$result));
    }


    public function beforeAction($action)
    {
        if (Yii::$app->session->has('lang')) {
            Yii::$app->language = Yii::$app->session->get('lang');
        } else {
            Yii::$app->language = 'ru-RU';
            Yii::$app->session->set('lang', 'ru-RU');
        }

        return parent::beforeAction($action);
    }

    public function actionGetLang(){
        $lang  = Yii::$app->session->get('lang');
        Yii::$app->response->format = Response::FORMAT_JSON;
        return Json::encode(['lang' => $lang]);
    }
}

views/layouts/header.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php $controller_name = Yii::$app->controller->id ?>
<?php $action_name =  Yii::$app->controller->action->id; ?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <? if ($controller_name == 'portfolio' && $action_name == 'index' || $action_name == 'details') { ?>
                <li class="active">
                    <a href="<?= Url::toRoute('/portfolio') ?>">
                        <span>Просмотр</span>
                    </a>
                </li>
                <? } else { ?>
                    <li>
                        <a href="<?= Url::toRoute('/portfolio') ?>">
                            <span>Просмотр</span>
                        </a>
                    </li>
                <? } ?>
                <? if ($action_name == 'load') { ?>
                <li class="active">
                    <a href="<?= Url::toRoute('/portfolio/load/') ?>">
                        <span>Загрузить</span>
                    </a>
                </li>
                <? } else { ?>
                <li>
                    <a href="<?= Url::toRoute('/portfolio/load/') ?>">
                        <span>Загрузить</span>
                    </a>
                </li>
                <? } ?>
            </ul>
            <a class="btn btn-danger btn-close" style="margin-top: 7px;" href="<?= Url::toRoute(['base/logout']) ?>">
                <?=\yii::t('layouts_header','exit')?>
            </a>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="foto_holder">
                        <?if(!empty($_SESSION['photo_pas'])):?>
                            <?= Html::img( WEB_SERVER_PATH_STUD_UPLOAD_PHOTO.$_SESSION['photo_pas'], ['class' => 'img_header', 'style' => 'margin-top: 5px; height: 40px;']) ?>
                        <?else:?>
                            <?= Html::img('/public/image/no-avatar.svg', [
                                'class' => 'img_header_teach',
                                'style' => 'margin-top: 5px; height: 40px;'
                            ]) ?>
                        <?endif;?>
                    </div>
                </li>
                <li>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

views/layouts/main.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">


    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap_to_all"></div>
<div class="navbar navbar-fixed-top" role="navigation">
    <?php $this->beginContent('@app/views/layouts/header.php'); ?>
    <?php $this->endContent(); ?>
</div>
<div class="container-fluid">
    <?= $content ?>
</div>
<div class='ajax-loader-overlay' style="display: none;"></div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main_login.php
<?php
use yii\helpers\Html;
use app\assets\LoginAsset;

/* @var $this \yii\web\View */
/* @var $content string */

LoginAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="container">
    <?= $content ?>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>